#!/bin/sh

if [ "x" == "x$JAVA_HOME" ]; then
  echo "Please set JAVA_HOME"
  exit 1
fi

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/"
APP_HOME="`pwd -P`"
cd "$SAVED"

$JAVA_HOME/bin/java -cp $JAVA_HOME/lib/tools.jar:$APP_HOME/jmx-stethoscope.jar jmx.Stethoscope $@